library(devtools)
library(roxygen2)

# Manual
devtools::document()

# Check and build
devtools::check()
devtools::build()


load_all(".")
library(tidyverse)
library(mvtnorm)
library(akima)
library(clue)
library(ggExtra)
library(gridExtra)
library(DescTools)


# Test cases
usethis::use_testthat()
devtools::test()

# Generated by roxygen2: do not edit by hand
#
# export(augment_matrix_random_block)
# export(calculate_tv_distance_empirical)
# export(entropy_pair)
# export(gaussian_copula_two_vars)
# export(genCDFInv_akima)
# export(genCDFInv_linear)
# export(genCDFInv_poly)
# export(genCDFInv_quantile)
# export(gen_number_1)
# export(gen_number_max)
# export(gen_number_min)
# export(generate_gaussian_copula_samples)
# export(generate_t_copula_samples)
# export(get_mutual_information)
# export(get_optimal_grid)
# export(get_simpsons_paradox_c)
# export(get_simpsons_paradox_d)
# export(get_target_corr)
# export(get_target_entropy)
# export(log_odds_dc)
# export(objective_function_SL)
# export(plot_log_odds)
# export(simulated_annealing_MI)
# export(simulated_annealing_SL)
# export(sinkhorn_algorithm)
# export(softmax)
# export(t_copula_two_vars)
# import(dplyr)
# import(ggplot2)
# importFrom(akima,aspline)
# importFrom(mvtnorm,rmvnorm)
# importFrom(mvtnorm,rmvt)
# importFrom(stats,pnorm)
# importFrom(stats,pt)
# importFrom(DescTools, ConDisPairs)
# importFrom(clue, solve_LSAP)
# importFrom(ggExtra, ggMarginal)
# importFrom(gridExtra, grid.arrange)
# importFrom("stats", "approxfun", "coef", "cor", "ecdf", "lm",
#            "predict", "quantile", "rnorm", "runif")
#
#
